### PR TITLE
fix: Token parsing issues if token contains delimiter

### PR DESCRIPTION
**Pull request by hariprasadiit**
#### Model

```
[request_definition]
r = sub, cid, lid, obj, act

[policy_definition]
p = sub, cid, lid, obj, act, rule, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub.id+'::'+r.sub.type, p.sub, r.cid+'::'+r.lid)&& eval(p.rule) && keyMatch(r.cid, p.cid)&& keyMatch(r.lid, p.lid) && regexMatch(r.act, p.act) && keyMatch2(r.obj, p.obj)
```

#### Policy

```
p, employee, *, *, /e/:eid, update, "r.sub.id == keyGet2(r.obj, p.obj, 'eid')"
p, employee, *, *, /e/:eid, get, true
p, admin, *, *, /e/:eid, update, true
p, admin, cid3, lid1, /kiosk/:kid, (get)|(update), true


g, admin, location-admin, *
g, location-admin, receptionist, *
g, receptionist, employee, *
g, billing-admin, employee, *
g, alice, admin, cid3::*
```

While loading above policy from database, `loadPolicyLine` from `Helper` class will parse `r.sub.id == keyGet2(r.obj, p.obj, 'eid')` into two tokens as it contains delimiter.

We can workaround this by wrapping `r.sub.id == keyGet2(r.obj, p.obj, 'eid')` with quotes but `hasPolicy` will fail because provided policy line contains extra quotes but parsed policy line will not have them.

### Solution

Wrap all tokens of policy line before joining them and passing policy line to the csv parser

### CODE REVIEW

**Comment by nodece** [comment]
thanks @hariprasadiit, please fix this CI errors.

**Comment by hariprasadiit** [comment]
@nodece I'm not really sure why coverage and tests are failing. On my system they're passing. Any help would be appreciated

**Comment by nodece** [comment]
please check this: https://github.com/node-casbin/typeorm-adapter/pull/46/checks?check_run_id=3562595276#step:7:36

**Comment by hariprasadiit** [comment]
@nodece fixed CI issues

**Review by Zxilly — APPROVED** [review]
lgtm

**Pull request merged**
